name: proyecto_tesina
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  dio: ^5.3.2
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  go_router: ^10.1.0
  pie_chart: ^5.3.2
  provider: ^6.0.5
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
